export const enum MS_BUTTON {
  MSBTN_NONE = -1,

  MSBTN_INFO,
  MSBTN_SOUND_BETS,
  MSBTN_BINGO_LIVE,
  MSBTN_UNDO_BETS,
  MSBTN_CANCEL_BETS,
  MSBTN_DOUBLE_BETS,
  MSBTN_REPEAT_BETS,

  MSBTN_CHIP_1,
  MSBTN_CHIP_5,
  MSBTN_CHIP_10,
  MSBTN_CHIP_25,
  MSBTN_CHIP_50,
  MSBTN_CHIP_100,

  //Thêm mới trước MSBTN_COUNT
  MSBTN_COUNT, //Số lượng button đang có
}
